const { HOST, PORT, HOOK_URL, PING_INTERVAL, LOG_FILE, TIMEZONE } = process.env

const ENABLE_DISCORD = (process.env.ENABLE_DISCORD === "true")

module.exports = {
    HOST, PORT, HOOK_URL, ENABLE_DISCORD, PING_INTERVAL, LOG_FILE, TIMEZONE
}
